name: Assign author to Pull request

on:
  pull_request:
    types: [ opened ]

jobs:
  assignAuthor:
    name: Assign author to PR
    runs-on: ubuntu-22.04
    steps:
      - name: Assign author to PR
        uses: technote-space/assign-author@v1
